# Generated by Django 5.0.6 on 2024-06-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accordionitem',
            name='header',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
