# Generated by Django 5.0.6 on 2024-06-18 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0002_alter_accordionitem_header_alter_section_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['id']},
        ),
    ]
