# Generated by Django 5.0.6 on 2024-06-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0003_alter_section_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='accordionitem',
            name='duration',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accordionitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
