# Generated by Django 5.0.6 on 2024-06-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0004_accordionitem_duration_accordionitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accordionitem',
            name='duration',
            field=models.CharField(choices=[('30', '30 minutes'), ('45', '45 minutes'), ('60', '60 minutes')], max_length=50),
        ),
    ]
