# Generated by Django 5.0.6 on 2024-06-20 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0007_treatment_delete_accordionitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='price',
        ),
    ]
