# Generated by Django 5.0.6 on 2024-06-20 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='treatment',
        ),
    ]
