# Generated by Django 5.0.6 on 2024-06-20 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_booking_treatment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='date_arrival',
        ),
        migrations.AddField(
            model_name='booking',
            name='date_leave',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
