# Generated by Django 5.0.6 on 2024-06-20 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'booking',
            '0003_rename_date_booking_date_arrival_booking_date_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time_arrival',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
