# Generated by Django 5.0.6 on 2024-06-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_carouselimage_paragraph_carouselimage_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselimage',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='carouselimage',
            old_name='paragraph',
            new_name='description',
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='title',
            field=models.CharField(default='default title', max_length=50),
        ),
    ]
