# Generated by Django 5.0.6 on 2024-06-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_welcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcome',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
