# Generated by Django 5.0.6 on 2024-06-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_carouselimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselimage',
            options={'ordering': ['title', 'order']},
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
