# Generated by Django 5.0.6 on 2024-06-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_discover'),
    ]

    operations = [
        migrations.AddField(
            model_name='discover',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='discover',
            name='paragraph1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='discover',
            name='paragraph2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='discover',
            name='paragraph3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='discover',
            name='paragraph4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='discover',
            name='paragraph5',
            field=models.TextField(blank=True),
        ),
    ]
