# Generated by Django 5.0.6 on 2024-06-19 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_discover_is_active_alter_discover_paragraph1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discover',
        ),
    ]
