# Generated by Django 5.0.6 on 2024-06-20 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_discover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselimage',
            name='description',
        ),
    ]
